services:
  postgres_server:
    image: postgres:13
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      odoo_network_compta:
        ipv4_address: 172.28.0.2

  odoo_server_compta:
    image: odoo:14
    environment:
      - HOST=172.28.0.2
      - USER=odoo
      - PASSWORD=odoo
      - STUDENT_PORTAL_JWT_SECRET=ebea25ac4b93122fa8e7e82dc173bd9d997021d3f72dbd75d0c900806a5692959850d845547bc5168aa594587677307a5da82f0adb4a1d5ce3e4cf87118d673c

    ports:
      - "8070:8069"
    networks:
      odoo_network_compta:
        ipv4_address: 172.28.0.3
    volumes:
      - odoo_server:/var/lib/odoo
      - "C:/Stages/espace_etudiant_backend_odoo14.0/custom-addons:/mnt/extra-addons"

networks:
  odoo_network_compta:
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres_data:
  odoo_server:
