from . import etudiant
from . import enseignant
from . import classe
from . import edt
from . import note
from . import parent
from . import absence
from . import reclamation
from . import reclamation_prof
from . import document
from . import matiere
from . import programme
from . import filiere
from . import niveau